# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 77e5468586df6ad767adb0ddacfafcdfb416f32e70c2630bcf7befa9ae256cc5489a9d900c89683e14b775c1b9ed53be39dea9259fb81a7d7e402d77f05b880c

test:
  secret_key_base: 75d9d9d7e9dd921b1295d7b08cb0bca103fed439a47c9b983e7387c2e49128ccbce6b59f58b55e6ddfa4e9eee0d63bd32a27ba07034b8393546c1fe0ae9255ab

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
